[Database]
#ConnectionString = "Server=localhost\SQLEXPRESS;Database=Test_colloquio;Trusted_Connection=True;TrustServerCertificate=True;"

[Ricerca]
#RicercaPredefinita = "RMN"
TipoRicercaPredefinita = "CodiceInterno"
